apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-prediction-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris-prediction-service
  template:
    metadata:
      labels:
        app: iris-prediction-service
    spec:
      serviceAccountName: iris-api
      containers:
      - name: iris-prediction-service
        image: us-central1-docker.pkg.dev/project-eada5958-ab21-4f76-b53/docker-images-repo/iris-api:latest
        ports:
        - containerPort: 8200
        readinessProbe:
          httpGet:
            path: /ready_check
            port: 8200
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /live_check
            port: 8200
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: "1000m"
            memory: "1Gi"
          limits:
            cpu: "5000m"
            memory: "2Gi"