apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: iris-prediction-service-hpa
spec:
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 60
        type: Utilization
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iris-prediction-service